LaundryIntent:
  speech:
    text: ""
  card:
    type: simple
    title: "Laundry Status"
    content: "Washer Status: {{ states.sensor.washer_state.state }}.\nDryer Status: {{ states.sensor.dryer_state.state }}"
  action:
    service: script.tts_say
    data_template:
      msg: >
        Hello, let me check the laundry for you.  The washer is {{ states.sensor.washer_state.state }}.  The Dryer is {{ states.sensor.dryer_state.state }}

TurnOnIntent:
  speech:
    text: "Yes Master.  Turning on {{ devicename }} {%- if 'christmas' in devicename.lower() -%}. Merry Christmas!{%- endif -%}"
  card:
    type: simple
    title: "Turn on {{ devicename }}"
    content: "Turned on {{ devicename }}"
  action:
    - service_template: >
        {%- if 'fireplace' in devicename.lower() -%}
          switch.toggle
        {%- elif 'living' in devicename.lower() -%}
          light.toggle
        {%- elif 'bedroom' in devicename.lower() -%}
          switch.toggle
        {%- elif 'christmas' in devicename.lower() -%}
          switch.toggle
        {%- elif 'ticker' in devicename.lower() -%}
          switch.toggle
        {%- elif 'scoreboard' in devicename.lower() -%}
          switch.toggle
        {%- else -%}
          {{ devicename }}
        {%- endif -%}
      data_template:
        entity_id: >
          {%- if 'fireplace' in devicename.lower() -%}
          switch.fireplace_switch
          {%- elif 'living' in devicename.lower() -%}
          light.leviton_vri061lx_multilevel_scene_switch_level
          {%- elif 'christmas' in devicename.lower() -%}
          switch.my_smart_plug
          {%- elif 'bedroom tv' in devicename.lower() -%}
          switch.bedroom_tv_power
          {%- elif 'bedroom light' in devicename.lower() -%}
          switch.leviton_vrs151lz_binary_scene_switch_switch_3
          {%- elif 'ticker' in devicename.lower() -%}
          switch.ticker
          {%- elif 'scoreboard' in devicename.lower() -%}
          switch.ticker
          {%- endif -%}

UnlockIntent:
  speech:
    text: "Yes Master.  Unlocking door"
  card:
    type: simple
    title: "Door Unlocked"
    content: "Your door is unlocked"
  action:
    service: lock.unlock
    entity_id: "lock.schlage_be469nxcen_touchscreen_deadbolt_locked"

WineRoomStatusIntent:
  speech:
    text: "Their are {{ states.input_number.wine_bottle_count.state | int }} bottles in storage.  The wine room is currently {{ states.climate.wine_room_temp.attributes.temperature }} degrees  with a humidity of {{ states.sensor.wine_room_humidity.state }} percent.  Perfect temperature for a glass of wine."
  card:
    type: simple
    title: "Wine Room"
    content: "Bottles: {{ states.input_number.wine_bottle_count.state | int }} Temp: {{ states.climate.wine_room_temp.attributes.temperature }} degrees  Humidity {{ states.sensor.wine_room_humidity.state }} percent."

WhoFarted:
  speech:
    text: ""
  card:
    type: simple
    title: "Who Farted?"
    content: "Let me ask Jarvis who farted."
  action:
    service: script.tts_say
    data:
      msg: "It was me Jarvis, and it was a nasty one."
