  - platform: mqtt
    name: "Fireplace Switch"
    state_topic: "ha/fireplace"
    command_topic: "myhome/fireplace"
    payload_on: "1"
    payload_off: "0"
    optimistic: false
  - platform: tplink
    host: 192.168.1.38
  - platform: tplink
    name: "Ticker"
    host: 192.168.1.19
  - platform: command_line
    switches:
      #toggles office Roku TV
      bedroom_tv_power:
        command_on: 'curl -X POST http://192.168.1.28:8060/keypress/PowerOn'
        command_off: 'curl -X POST http://192.168.1.28:8060/keypress/PowerOff'
        command_state: 'curl -s GET http://192.168.1.28:8060/query/device-info | grep power-mode | sed -e "s:<power-mode>DisplayOff</power-mode>:OFF:" -e "s:<power-mode>PowerOn</power-mode>:ON:"'
        value_template: '{{ value == "ON" }}'
